In [67]:
from pathlib import Path
import polars as pl
pl.Config.set_tbl_cols(-1)          # 显示全部列
pl.Config.set_tbl_width_chars(-1)   # 不限制表格总宽度

polars.config.Config

In [53]:
DATE = "20260624"
ROOT = Path("/data/xujiayi/xjy/l2")
EXCHANGE = "sz"
LEVELS = 10

# 浮点价格允许的误差
PRICE_TOLERANCE = 1e-8

# 数量理论上应完全一致；如有需要可改成1等其他值
QTY_TOLERANCE = 0.0

In [54]:
def null_safe_close(
    left: pl.Expr,
    right: pl.Expr,
    tolerance: float,
) -> pl.Expr:
    """两个值都为空，或者数值误差不超过 tolerance，即认为一致。"""
    return (
        (left.is_null() & right.is_null())
        | ((left - right).abs() <= tolerance)
    ).fill_null(False)


def to_float(column: str) -> pl.Expr:
    """兼容数字列以及包含双引号的字符串数字列。"""
    return (
        pl.col(column)
        .cast(pl.String)
        .str.strip_chars('"')
        .cast(pl.Float64, strict=False)
        .alias(column)
    )

In [55]:
# =============================================================================
# 1. 读取自己生成的快照
# =============================================================================

my_path = ROOT / "proc" / DATE / f"{EXCHANGE}shot_1m.pq"

my_shot = (
    pl.read_parquet(my_path)
    .with_columns(
        pl.col("SecurityID").cast(pl.Int64),
        pl.col("BarTime").cast(pl.Time),
    )
    .sort(["SecurityID", "BarTime"])
)

In [57]:
# =============================================================================
# 2. 读取官方快照
# =============================================================================

official_path = ROOT / "raw" / DATE / f"{EXCHANGE}shot.pq"

official_columns = ["UpdateTime", "SecurityID"]

for level in range(1, LEVELS + 1):
    official_columns.extend([
        f"BidPrice{level}",
        f"BidVolume{level}",
        f"AskPrice{level}",
        f"AskVolume{level}",
    ])

official_shot = (
    pl.read_parquet(official_path)
    .filter(pl.col("MDStreamID") == 10)
    .select(official_columns)
    .with_columns(
        pl.col("SecurityID").cast(pl.Int64),
        pl.col("UpdateTime").str.to_time(),
    )
    .with_columns([
        to_float(column)
        for column in official_columns
        if column not in {"UpdateTime", "SecurityID"}
    ])
    .sort(["SecurityID", "UpdateTime"])
)

In [58]:
# =============================================================================
# 3. 将官方快照对齐到自己生成的 BarTime
#
# 对每只证券、每个bar，选择：
#     UpdateTime <= BarTime
# 的最后一条官方快照。
# =============================================================================

bar_grid = (
    my_shot
    .select(["SecurityID", "BarTime"])
    .unique()
    .sort(["SecurityID", "BarTime"])
)

official_aligned = (
    bar_grid
    .join_asof(
        official_shot,
        left_on="BarTime",
        right_on="UpdateTime",
        by="SecurityID",
        strategy="backward",
        check_sortedness=False,
    )
    .with_columns(
        (
            (
                pl.col("BarTime").cast(pl.Int64)
                - pl.col("UpdateTime").cast(pl.Int64)
            )
            / 1_000_000_000
        ).alias("OfficialTimeGapSeconds")
    )
)

In [59]:
official_aligned.filter(pl.col('SecurityID') == 1).filter(
    (pl.col('BarTime')>=pl.time(9,30)) & (pl.col('BarTime')<=pl.time(15,0))
)

shape: (241, 44)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SecurityI ┆ BarTime  ┆ UpdateTim ┆ BidPrice1 ┆ … ┆ BidVolume ┆ AskPrice1 ┆ AskVolume ┆ OfficialT │
│ D         ┆ ---      ┆ e         ┆ ---       ┆   ┆ 10        ┆ 0         ┆ 10        ┆ imeGapSec │
│ ---       ┆ time     ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ onds      │
│ i64       ┆          ┆ time      ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 09:30:00 ┆ 09:30:00  ┆ 10.67     ┆ … ┆ 30000.0   ┆ 10.77     ┆ 74200.0   ┆ 0.0       │
│ 1         ┆ 09:31:00 ┆ 09:31:00  ┆ 10.65     ┆ … ┆ 99400.0   ┆ 10.75     ┆ 88000.0   ┆ 0.0       │
│ 1         ┆ 09:32:00 ┆ 09:32:00  ┆ 10.67     ┆ … ┆ 101300.0  ┆ 10.77     ┆ 83200.0   ┆ 0.0       │
│ 1         ┆ 09:33:00 ┆ 09:33:00  ┆ 10.68     ┆ … ┆ 100500.0  ┆ 10.78     ┆ 230100.0  ┆ 0.0       │
│ 1         ┆ 09:34:00 ┆ 09:34:00  ┆ 10.69     ┆ … ┆ 517200.0  ┆ 10.79     ┆ 207600.0  ┆ 0.0       │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1         ┆ 14:56:00 ┆ 14:56:00  ┆ 10.52     ┆ … ┆ 191800.0  ┆ 10.62     ┆ 121800.0  ┆ 0.0       │
│ 1         ┆ 14:57:00 ┆ 14:57:00  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.0       │
│ 1         ┆ 14:58:00 ┆ 14:57:54  ┆ 10.54     ┆ … ┆ null      ┆ null      ┆ null      ┆ 6.0       │
│ 1         ┆ 14:59:00 ┆ 14:58:57  ┆ 10.55     ┆ … ┆ null      ┆ null      ┆ null      ┆ 3.0       │
│ 1         ┆ 15:00:00 ┆ 15:00:00  ┆ 10.51     ┆ … ┆ 263700.0  ┆ 10.61     ┆ 61300.0   ┆ 0.0       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [60]:
my_shot.filter(pl.col('SecurityID') == 1).filter(
    (pl.col('BarTime')>=pl.time(9,30)) & (pl.col('BarTime')<=pl.time(15,0))
)

shape: (241, 42)
┌──────────┬────────────┬───────────┬────────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidQty1    ┆ … ┆ BidPrice1 ┆ BidQty10 ┆ AskPrice1 ┆ AskQty10 │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ 0         ┆ ---      ┆ 0         ┆ ---      │
│ time     ┆ i64        ┆ f64       ┆ f64        ┆   ┆ ---       ┆ f64      ┆ ---       ┆ f64      │
│          ┆            ┆           ┆            ┆   ┆ f64       ┆          ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ 09:30:00 ┆ 1          ┆ 10.68     ┆ 41300.0    ┆ … ┆ 10.59     ┆ 79500.0  ┆ 10.78     ┆ 66500.0  │
│ 09:31:00 ┆ 1          ┆ 10.65     ┆ 392900.0   ┆ … ┆ 10.56     ┆ 99400.0  ┆ 10.75     ┆ 88000.0  │
│ 09:32:00 ┆ 1          ┆ 10.67     ┆ 12000.0    ┆ … ┆ 10.58     ┆ 101300.0 ┆ 10.77     ┆ 83200.0  │
│ 09:33:00 ┆ 1          ┆ 10.68     ┆ 15200.0    ┆ … ┆ 10.59     ┆ 100500.0 ┆ 10.78     ┆ 230100.0 │
│ 09:34:00 ┆ 1          ┆ 10.69     ┆ 2300.0     ┆ … ┆ 10.6      ┆ 517200.0 ┆ 10.79     ┆ 207600.0 │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ 14:56:00 ┆ 1          ┆ 10.52     ┆ 95600.0    ┆ … ┆ 10.43     ┆ 191800.0 ┆ 10.62     ┆ 121800.0 │
│ 14:57:00 ┆ 1          ┆ 10.53     ┆ 100.0      ┆ … ┆ 10.44     ┆ 49900.0  ┆ 10.63     ┆ 85000.0  │
│ 14:58:00 ┆ 1          ┆ 11.78     ┆ 3500.0     ┆ … ┆ 10.54     ┆ 49600.0  ┆ 10.5      ┆ 7600.0   │
│ 14:59:00 ┆ 1          ┆ 11.78     ┆ 3600.0     ┆ … ┆ 10.58     ┆ 5200.0   ┆ 10.5      ┆ 8100.0   │
│ 15:00:00 ┆ 1          ┆ 10.51     ┆ 1.016877e6 ┆ … ┆ 10.42     ┆ 263700.0 ┆ 10.61     ┆ 61300.0  │
└──────────┴────────────┴───────────┴────────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [61]:
# =============================================================================
# 4. 修改官方字段名，避免和自己的字段重名
# =============================================================================

official_rename = {}

for level in range(1, LEVELS + 1):
    official_rename.update({
        f"BidPrice{level}": f"OfficialBidPrice{level}",
        f"BidVolume{level}": f"OfficialBidQty{level}",
        f"AskPrice{level}": f"OfficialAskPrice{level}",
        f"AskVolume{level}": f"OfficialAskQty{level}",
    })

official_aligned = official_aligned.rename(official_rename)


# =============================================================================
# 5. 合并自己生成的快照和官方快照
# =============================================================================

comparison = my_shot.join(
    official_aligned,
    on=["SecurityID", "BarTime"],
    how="left",
)

In [ ]:
# =============================================================================
# 6. 逐档计算差值和是否一致
# =============================================================================

difference_expressions = []
match_expressions = []
match_columns = []

for level in range(1, LEVELS + 1):
    pairs = [
        (
            f"BidPrice{level}",
            f"OfficialBidPrice{level}",
            PRICE_TOLERANCE,
        ),
        (
            f"BidQty{level}",
            f"OfficialBidQty{level}",
            QTY_TOLERANCE,
        ),
        (
            f"AskPrice{level}",
            f"OfficialAskPrice{level}",
            PRICE_TOLERANCE,
        ),
        (
            f"AskQty{level}",
            f"OfficialAskQty{level}",
            QTY_TOLERANCE,
        ),
    ]

    for my_column, official_column, tolerance in pairs:
        diff_column = f"{my_column}Diff"
        match_column = f"{my_column}Match"

        difference_expressions.append(
            (
                pl.col(my_column)
                - pl.col(official_column)
            ).alias(diff_column)
        )

        match_expressions.append(
            null_safe_close(
                pl.col(my_column),
                pl.col(official_column),
                tolerance,
            ).alias(match_column)
        )

        match_columns.append(match_column)

comparison = (
    comparison
    .with_columns(difference_expressions)
    .with_columns(match_expressions)
    .with_columns(
        pl.all_horizontal(match_columns).alias("AllLevelsMatch")
    )
)

In [ ]:
# =============================================================================
# 7. 总体匹配率
# =============================================================================

summary_expressions = [
    pl.len().alias("RowCount"),
    pl.col("UpdateTime").is_not_null().sum().alias("OfficialMatchedRows"),
    pl.col("AllLevelsMatch").sum().alias("AllLevelsMatchedRows"),
    pl.col("AllLevelsMatch").mean().alias("AllLevelsMatchRate"),
]

for level in range(1, LEVELS + 1):
    for column in (
        f"BidPrice{level}",
        f"BidQty{level}",
        f"AskPrice{level}",
        f"AskQty{level}",
    ):
        summary_expressions.append(
            pl.col(f"{column}Match")
            .mean()
            .alias(f"{column}MatchRate")
        )

summary = comparison.select(summary_expressions)

print("总体匹配情况：")
print(summary)

In [64]:
# =============================================================================
# 8. 每一档的匹配率
# =============================================================================

level_summary_rows = []

for level in range(1, LEVELS + 1):
    result = comparison.select(
        pl.lit(level).alias("Level"),
        pl.col(f"BidPrice{level}Match").mean().alias("BidPriceMatchRate"),
        pl.col(f"BidQty{level}Match").mean().alias("BidQtyMatchRate"),
        pl.col(f"AskPrice{level}Match").mean().alias("AskPriceMatchRate"),
        pl.col(f"AskQty{level}Match").mean().alias("AskQtyMatchRate"),
    )

    level_summary_rows.append(result)

level_summary = pl.concat(level_summary_rows)

print("逐档匹配率：")
print(level_summary)

逐档匹配率：
shape: (10, 5)
┌───────┬───────────────────┬─────────────────┬───────────────────┬─────────────────┐
│ Level ┆ BidPriceMatchRate ┆ BidQtyMatchRate ┆ AskPriceMatchRate ┆ AskQtyMatchRate │
│ ---   ┆ ---               ┆ ---             ┆ ---               ┆ ---             │
│ i32   ┆ f64               ┆ f64             ┆ f64               ┆ f64             │
╞═══════╪═══════════════════╪═════════════════╪═══════════════════╪═════════════════╡
│ 1     ┆ 0.855936          ┆ 0.693188        ┆ 0.856996          ┆ 0.688568        │
│ 2     ┆ 0.84962           ┆ 0.79684         ┆ 0.851204          ┆ 0.795862        │
│ 3     ┆ 0.8479            ┆ 0.815896        ┆ 0.849526          ┆ 0.818204        │
│ 4     ┆ 0.846656          ┆ 0.829041        ┆ 0.848054          ┆ 0.831726        │
│ 5     ┆ 0.845897          ┆ 0.836541        ┆ 0.847216          ┆ 0.839068        │
│ 6     ┆ 0.845602          ┆ 0.840696        ┆ 0.846677          ┆ 0.843056        │
│ 7     ┆ 0.845561          ┆ 0.843939        ┆ 0.846362          ┆ 0.845366        │
│ 8     ┆ 0.845727          ┆ 0.846019        ┆ 0.846349          ┆ 0.847219        │
│ 9     ┆ 0.845851          ┆ 0.847288        ┆ 0.846428          ┆ 0.848753        │
│ 10    ┆ 0.846252          ┆ 0.84865         ┆ 0.8467            ┆ 0.849687        │
└───────┴───────────────────┴─────────────────┴───────────────────┴─────────────────┘

In [65]:
# =============================================================================
# 9. 找出前两档不一致的记录
# =============================================================================

first_two_match_columns = []

for level in range(1, 3):
    first_two_match_columns.extend([
        f"BidPrice{level}Match",
        f"BidQty{level}Match",
        f"AskPrice{level}Match",
        f"AskQty{level}Match",
    ])

first_two_mismatches = (
    comparison
    .filter(
        ~pl.all_horizontal(first_two_match_columns)
    )
    .select([
        "BarTime",
        "UpdateTime",
        "OfficialTimeGapSeconds",
        "SecurityID",

        "BidPrice1",
        "OfficialBidPrice1",
        "BidPrice1Diff",
        "BidQty1",
        "OfficialBidQty1",
        "BidQty1Diff",

        "AskPrice1",
        "OfficialAskPrice1",
        "AskPrice1Diff",
        "AskQty1",
        "OfficialAskQty1",
        "AskQty1Diff",

        "BidPrice2",
        "OfficialBidPrice2",
        "BidPrice2Diff",
        "BidQty2",
        "OfficialBidQty2",
        "BidQty2Diff",

        "AskPrice2",
        "OfficialAskPrice2",
        "AskPrice2Diff",
        "AskQty2",
        "OfficialAskQty2",
        "AskQty2Diff",
    ])
    .sort(["SecurityID", "BarTime"])
)

print("前两档不一致记录：")
print(first_two_mismatches)

前两档不一致记录：
shape: (487_385, 28)
┌──────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ BarTime  ┆ UpdateTime ┆ OfficialTi ┆ SecurityI ┆ … ┆ AskPrice2 ┆ AskQty2 ┆ OfficialA ┆ AskQty2Di │
│ ---      ┆ ---        ┆ meGapSecon ┆ D         ┆   ┆ Diff      ┆ ---     ┆ skQty2    ┆ ff        │
│ time     ┆ time       ┆ ds         ┆ ---       ┆   ┆ ---       ┆ f64     ┆ ---       ┆ ---       │
│          ┆            ┆ ---        ┆ i64       ┆   ┆ f64       ┆         ┆ f64       ┆ f64       │
│          ┆            ┆ f64        ┆           ┆   ┆           ┆         ┆           ┆           │
╞══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 09:16:00 ┆ 09:15:54   ┆ 6.0        ┆ 1         ┆ … ┆ 10.02     ┆ 100.0   ┆ 1800.0    ┆ -1700.0   │
│ 09:17:00 ┆ 09:16:57   ┆ 3.0        ┆ 1         ┆ … ┆ 10.02     ┆ 100.0   ┆ 3700.0    ┆ -3600.0   │
│ 09:18:00 ┆ 09:18:00   ┆ 0.0        ┆ 1         ┆ … ┆ null      ┆ 100.0   ┆ null      ┆ null      │
│ 09:19:00 ┆ 09:18:45   ┆ 15.0       ┆ 1         ┆ … ┆ null      ┆ 100.0   ┆ null      ┆ null      │
│ 09:20:00 ┆ 09:20:00   ┆ 0.0        ┆ 1         ┆ … ┆ null      ┆ 100.0   ┆ null      ┆ null      │
│ …        ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ 14:55:00 ┆ 14:55:00   ┆ 0.0        ┆ 302132    ┆ … ┆ 0.0       ┆ 1000.0  ┆ 1000.0    ┆ 0.0       │
│ 14:56:00 ┆ 14:56:00   ┆ 0.0        ┆ 302132    ┆ … ┆ -0.02     ┆ 400.0   ┆ 100.0     ┆ 300.0     │
│ 14:57:00 ┆ 14:57:00   ┆ 0.0        ┆ 302132    ┆ … ┆ null      ┆ 7400.0  ┆ null      ┆ null      │
│ 14:58:00 ┆ 14:57:54   ┆ 6.0        ┆ 302132    ┆ … ┆ null      ┆ 300.0   ┆ null      ┆ null      │
│ 14:59:00 ┆ 14:58:57   ┆ 3.0        ┆ 302132    ┆ … ┆ null      ┆ 300.0   ┆ null      ┆ null      │
└──────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [68]:
# =============================================================================
# 10. 单独检查某只证券、某个bar
# =============================================================================

sample = comparison.filter(
    (pl.col("SecurityID") == 1)
    & (pl.col("BarTime") == pl.time(14, 56))
).select([
    "SecurityID",
    "BarTime",
    "UpdateTime",
    "OfficialTimeGapSeconds",

    "BidPrice1",
    "OfficialBidPrice1",
    "BidQty1",
    "OfficialBidQty1",

    "AskPrice1",
    "OfficialAskPrice1",
    "AskQty1",
    "OfficialAskQty1",

    "BidPrice2",
    "OfficialBidPrice2",
    "BidQty2",
    "OfficialBidQty2",

    "AskPrice2",
    "OfficialAskPrice2",
    "AskQty2",
    "OfficialAskQty2",
])

print("单条样本：")
print(sample)

单条样本：
shape: (1, 20)
┌────────────┬──────────┬────────────┬────────────────────────┬───────────┬───────────────────┬─────────┬─────────────────┬───────────┬───────────────────┬─────────┬─────────────────┬───────────┬───────────────────┬──────────┬─────────────────┬───────────┬───────────────────┬──────────┬─────────────────┐
│ SecurityID ┆ BarTime  ┆ UpdateTime ┆ OfficialTimeGapSeconds ┆ BidPrice1 ┆ OfficialBidPrice1 ┆ BidQty1 ┆ OfficialBidQty1 ┆ AskPrice1 ┆ OfficialAskPrice1 ┆ AskQty1 ┆ OfficialAskQty1 ┆ BidPrice2 ┆ OfficialBidPrice2 ┆ BidQty2  ┆ OfficialBidQty2 ┆ AskPrice2 ┆ OfficialAskPrice2 ┆ AskQty2  ┆ OfficialAskQty2 │
│ ---        ┆ ---      ┆ ---        ┆ ---                    ┆ ---       ┆ ---               ┆ ---     ┆ ---             ┆ ---       ┆ ---               ┆ ---     ┆ ---             ┆ ---       ┆ ---               ┆ ---      ┆ ---             ┆ ---       ┆ ---               ┆ ---      ┆ ---             │
│ i64        ┆ time     ┆ time       ┆ f64                    ┆ f64       ┆ f64               ┆ f64     ┆ f64             ┆ f64       ┆ f64               ┆ f64     ┆ f64             ┆ f64       ┆ f64               ┆ f64      ┆ f64             ┆ f64       ┆ f64               ┆ f64      ┆ f64             │
╞════════════╪══════════╪════════════╪════════════════════════╪═══════════╪═══════════════════╪═════════╪═════════════════╪═══════════╪═══════════════════╪═════════╪═════════════════╪═══════════╪═══════════════════╪══════════╪═════════════════╪═══════════╪═══════════════════╪══════════╪═════════════════╡
│ 1          ┆ 14:56:00 ┆ 14:56:00   ┆ 0.0                    ┆ 10.52     ┆ 10.52             ┆ 95600.0 ┆ 95600.0         ┆ 10.53     ┆ 10.53             ┆ 29900.0 ┆ 29600.0         ┆ 10.51     ┆ 10.51             ┆ 1.0419e6 ┆ 1.0419e6        ┆ 10.54     ┆ 10.54             ┆ 157700.0 ┆ 160900.0        │
└────────────┴──────────┴────────────┴────────────────────────┴───────────┴───────────────────┴─────────┴─────────────────┴───────────┴───────────────────┴─────────┴─────────────────┴───────────┴───────────────────┴──────────┴─────────────────┴───────────┴───────────────────┴──────────┴─────────────────┘